version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile

        container_name: coding4beginner
        volumes:
            - ../Playground:/workspace/playground
            - ../Lessons:/workspace/lessons
            - ../../Workspace:/workspace/mywork
            - ../../Courses:/workspace/courses
        ports:
            - 8000:8000
            - 8008:8080

        environment:
            - DJANGO_DEBUG=1

        command: /bin/sh -c "while sleep 1000; do :; done"
