version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile

        container_name: devenv-codetogether
        volumes:
            - ..:/HERE
            - ../Courses:/workspace/courses
            - ../Lessons:/workspace/lessons
            - ../Notebooks:/workspace/notebooks
            - ../Repositories:/workspace/repositories
            
            
        ports:
            - 8000:8000

        environment:
            - DJANGO_DEBUG=1

        command: /bin/sh -c "while sleep 1000; do :; done"
