version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile

        container_name: devenv-coding4girls
        volumes:
            - ../:/workspace/playground
            
        ports:
            - 8000:8000

        environment:
            - DJANGO_DEBUG=1

        command: /bin/sh -c "while sleep 1000; do :; done"
