version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile

        container_name: coding4beginner
        volumes:
            - ../../Lessons:/coding4beginner/lessons
            - ../../Workspace:/coding4beginner/workspace
            - ../../Courses:/coding4beginner/courses
        ports:
            - 8000:8000
            - 8008:8080

        environment:
            - DJANGO_DEBUG=1

        command: /bin/sh -c "while sleep 1000; do :; done"
